### ISSUE TITLE
index file error near the end of a popins call

### ISSUE THREAD

**Issue by jbsysadmin** [bkehr/popins#1]
Greetings. 
We have a user report that when running the command below, the process fails with a bwa error.
Environment includes Centos 6.8, kernel  2.6.32-504.12.2.

Command:
_/path_to_popins/popins assemble --sample sample1 --reference <file1>.fa <file2>.bam_

Error:
_[PopIns 2017-04-13 16:46:50] Remapping unmapped reads using /path_to_bwa-0.7.15/bwa
[E::bwa_idx_load_from_disk] fail to locate the index files_

Do you have any leads  on how the user can proceed without error?
There is  a  sampel directory created. If the user tries a  second run, with that  directory removed, this  error will occur. But if the directory is  present, the process will conclude without incident.

Final output: (snippet)

_[46.062945] Writing into graph file ./sample1/assembly/LastGraph...
[46.288882] Estimated Coverage = 3.699115
Final graph has 7437 nodes and n50 of 244, max 3512, total 930900, using 109325/828772 reads
[PopIns 2017-04-13 16:19:25] popins assemble finished in 74 seconds._

**Comment by bkehr** [comment]
Thanks for reporting your issue.

Are the BWA index files present for the fasta file specified with the `--reference` option?
If not, does creating them solve your problem?

    bwa index /path_to/file.fa

The second run when the sample directory is present skips the realignment step and assumes that it has completed before. The results should resemble those you would obtain without specifying the `--reference` option. I assume this is not what you intend to do.
