### ISSUE TITLE
Problem about place-refalign

### ISSUE THREAD

**Issue by Bioinfoq** [bkehr/popins#12]
Dear Sir,

When excuting the comman popins place-refalign, I cannot get any contigs from supercontigs obtained by popins merge.

The result is as follows, [PopIns 2019-06-14 16:37:44] Reading contig sequences from supercontigs.fa. Loaded 0 contig sequences.

I read the function named LoadContigs in popins_place.h. And I found the contigSet saved the aligned reference sequence name but id represented the names of supercontigs. So, the result of contigSet.count(id) would be 0 and no information would be appended to the variable called contig. I think that is the reason why no contigs sequences would be loaded. The graph of LoadContigs function is attached for your kind perusal.
![image](https://user-images.githubusercontent.com/51524879/59499774-a720e680-8eca-11e9-8b05-926f6ef59021.png)

Could you give me some advice? Thank you very much!

**Comment by bkehr** [comment]
Dear Bioinfoq,

could you give me the commands you used to run popins, as well as the first few lines of  your input files (genome.fa, locations.txt) for me to make a guess what is going wrong?

Thanks!

PS: Please do not assume that GitHub is used by men only.

**Comment by bkehr** [comment]
I am closing this issue since I did not receive a reply within 6 months. Please reopen in case the problem persists.
