### ISSUE TITLE
Problems with popins place-refalign: terminate called after throwing an instance of 'seqan::UnexpectedEnd'   what():  Unexpected end of input.

### ISSUE THREAD

**Issue by Zhiliang-Zhang** [bkehr/popins#13]
Dear Dr. bkehr,

I have received an error message as following when ran "popins place-refalign".

[PopIns 2019-12-18 21:10:05] Listing locations files.
[PopIns 2019-12-18 21:10:05] Merging 10 locations files.
[PopIns 2019-12-18 21:10:56] Reading locations from locations.txt
[PopIns 2019-12-18 21:11:13] Loaded 325847 locations that pass filters.
[PopIns 2019-12-18 21:11:13] Reading contig sequences from supercontigs.fa
[PopIns 2019-12-18 21:11:15] Loaded 242129 contig sequences.
[PopIns 2019-12-18 21:11:19] Aligning contigs to reference
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*****************terminate called after throwing an instance of 'seqan::UnexpectedEnd'
  what():  Unexpected end of input.

This error resulted in missing "locations_placed.txt & locations_unplaced.txt" file.

Could you give me some advice? Thanks!

Zhiliang

![image](https://user-images.githubusercontent.com/24313587/71182379-f51b0a80-22b0-11ea-8714-a238130ee154.png)

**Comment by bkehr** [comment]
Dear Zhiliang,

Thanks for reporting the issue. I assume you cannot provide me with the input files to reproduce the error? Would it be possible for you to send me the file ``locations.txt``?

Birte

**Comment by Zhiliang-Zhang** [comment]
> Dear Zhiliang,
> 
> Thanks for reporting the issue. I assume you cannot provide me with the input files to reproduce the error? Would it be possible for you to send me the file `locations.txt`?
> 
> Birte

Dear Dr. bkehr,

Thanks for your response! The file `locations.txt` have 5443588 lines & 457M. Here are some of the contents:

![WeChata46be995cd2f1080c1a5141dbb02d161](https://user-images.githubusercontent.com/24313587/71704482-a7a4ae80-2e15-11ea-987b-1e78568ba191.png)

Zhiliang

**Comment by bkehr** [comment]
Dear Zhiliang,

after looking into this for a bit, I made a first guess where the error might occur. I commited some changes to catch the ``UnexpectedEnd`` exception in one place.

I cannot promise without reproducing the error that this solves your problem. But it would be great if you could give it a try, i.e. pull the latest changes from the master branch, compile PopIns again, and run the place-refalign command. Does the error message change?

Thanks,
Birte

**Comment by Zhiliang-Zhang** [comment]
> Dear Zhiliang,
> 
> after looking into this for a bit, I made a first guess where the error might occur. I commited some changes to catch the `UnexpectedEnd` exception in one place.
> 
> I cannot promise without reproducing the error that this solves your problem. But it would be great if you could give it a try, i.e. pull the latest changes from the master branch, compile PopIns again, and run the place-refalign command. Does the error message change?
> 
> Thanks,
> Birte

Dear Dr. bkehr,

The error message have changed as following after re-compile PopIns with the latest changes from the master branch. And I have re-built the genome FAI index, ran the place-refalign command and solved this problem. I am running the place-splitalign command now.

![image](https://user-images.githubusercontent.com/24313587/71724144-262b3b80-2e6a-11ea-9589-a29af9845618.png)

Thank you for your kind help!

Zhiliang

**Comment by bkehr** [comment]
Dear Zhiliang,

Great to hear that you could solve the problem with the new error message by rebuilding the genome's FAI index. Sorry for the uninformative error message before.

Birte
