### ISSUE TITLE
Problems with popins assemble: sh: velveth-63: command not found

### ISSUE THREAD

**Issue by Zhiliang-Zhang** [bkehr/popins#14]
Dear Dr. bkehr,

I have received an error message as following when ran "popins assemble".

sh: velveth-63: command not found
ERROR while preparing assembly with velveth-63 of ./TW0057/filtered.single.fastq, ./TW0057/filtered.paired.1.fastq, and ./TW0057/filtered.paired.2.fastq

Could you give me some advice? Thanks!

Zhiliang
![image](https://user-images.githubusercontent.com/24313587/72420049-f7da2400-37b8-11ea-9a91-5e5773c80f66.png)

**Comment by bkehr** [comment]
Dear Zhiliang,

do you have velvet installed? Please set the path to your installation in the popins.config file, e.g.

```
VELVETH := velveth
VELVETG := velvetg
```

if they are installed in a location that is in your PATH variable or otherwise

```
VELVETH := /path/to/velveth
VELVETG := /path/to/velvetg
```

Please let me know if that solves your problem.

Birte

**Comment by Zhiliang-Zhang** [comment]
> Dear Zhiliang,
> 
> do you have velvet installed? Please set the path to your installation in the popins.config file, e.g.
> 
> ```
> VELVETH := velveth
> VELVETG := velvetg
> ```
> 
> if they are installed in a location that is in your PATH variable or otherwise
> 
> ```
> VELVETH := /path/to/velveth
> VELVETG := /path/to/velvetg
> ```
> 
> Please let me know if that solves your problem.
> 
> Birte

Dear Dr. bkehr,

Apologies for the delayed response after a half month holiday. 

I was re-compile PopIns with your advice and solved that problem. But I got a new issue as following when I assembled a ~560GB bam sample(~33X). 

![image](https://user-images.githubusercontent.com/24313587/73664691-cb8c3600-46da-11ea-8c7a-e12e4426565a.png)

![image](https://user-images.githubusercontent.com/24313587/73664470-718b7080-46da-11ea-8d7f-86463c2d4e45.png)

The same error from running velvetg-command:
![image](https://user-images.githubusercontent.com/24313587/73759640-330fb780-47a7-11ea-9937-674ef6fb11d1.png)

Could you give me some advice? Thanks!

Zhiliang

**Comment by bkehr** [comment]
Dear Zhiliang,

This is an error message from velvet. With such a large bam file, I would guess that you do not have sufficient memory available on your machine to run the assembly. Please turn to the velvet authors if more memory does not solve your problem.

Birte
