### ISSUE TITLE
Problems with popins merge

### ISSUE THREAD

**Issue by Zhiliang-Zhang** [bkehr/popins#15]
Dear Dr. bkehr,

I got a new error message as following when ran "popins merge" (379 samples, the size of contigs.fa per sample: 24M~153M).

![image](https://user-images.githubusercontent.com/24313587/74020940-90894b80-49d5-11ea-8599-8a82ea096ad6.png)

This error resulted in missing "supercontig.fa" file.

Zhiliang

**Comment by bkehr** [comment]
Dear Zhiliang,

the error (std::bad_alloc) indicates that you are not using enough memory to process this number of samples with such a large number of contigs per sample.

Are you processing human samples? Did you use an alternative reference in popins' assemble command to filter bacterial and viral sequences? If not, I strongly recommend to do so.

In comparison, we obtained between 10,000 and 40,000 contigs per sample in our analysis of 15,219 Icelanders (see Supplementary Note Figure 2 on page 12 of the [Supplementary Text and Figures](https://static-content.springer.com/esm/art%3A10.1038%2Fng.3801/MediaObjects/41588_2017_BFng3801_MOESM37_ESM.pdf)).

Birte
