### ISSUE TITLE
[improvement] running popins on species other than human

### ISSUE THREAD

**Issue by Krannich479** [bkehr/popins#18]
@bkehr Since release update v1.0.1 popins is supposed to run on non-human species too. Has this been tested at some point? I noticed some minor things like [checking for human chromosome numbers](https://github.com/bkehr/popins/blob/master/assemble/crop_unmapped.h#L41) that might fail at some point.

**Comment by bkehr** [comment]
I have not tested running PopIns on other species myself but I do not see a reason why it should fail.

The variable that is named `humanSeqs` stores the number of sequences specified using the --filter option, i.e. the number of human sequences in the alternate reference file when analysing human genomes or the number of mouse sequences in the alternate reference file when analysing mouse genomes etc. Thus, it should work for other species, too.
