### ISSUE TITLE
Error when running contig map and genotype

### ISSUE THREAD

**Issue by AnnaAlk** [bkehr/popins#2]
When running the genotype command, the process fails with an error below:

popins genotype --reference hs37d5.fa Sample1
[PopIns 2017-04-20 14:08:31] Opening input files.
terminate called after throwing an instance of 'seqan::ParseError'
  what():  Not enough fields.
Aborted (core dumped)

Also we paid attention to the additional error during the contigmap step which didn't fail the process:

[bam_merge_core] Order of targets in file ./Sample1/merged.bam.tmp.000.bam caused coordinate sort to be lost

**Comment by bkehr** [comment]
Hi AnnaAlk,

we have not seen this error before and need a little more information to find out what is going wrong.

- Can you provide the list of files and their sizes in the sample directory `./Sample1`?
- What version of samtools are you using?
- Have you run the placing steps after the contigmap step?
- Most likely, something is wrong with the file `insertions.vcf`, which is created in the placing steps. Would it be possible for you to attach the file or send it to us by email?

Thanks,
Birte

**Comment by AnnaAlk** [comment]
You have a Secure Message From Columbia University Medical Center. Click this link to view your message on a mobile device https://securemail.cumc.columbia.edu/formpostdir/securereader?id=glm6LqoD3su50df4LAJxtfF1vkF2-Z4m&brand=7fc8e138 by 2017-05-01 09:38 EDT to read your message.   If you are not using a mobile device, open the attachment called SecureMessageAtt.html. <p> If you are still having trouble viewing the message, go to http://www.cumc.columbia.edu/it/howto/encrypt/secure-email.html for further assistance.

**Comment by bkehr** [comment]
Thanks for the information and file. I can reproduce the reported error with your file when I include SeqAn 2.3.x instead of SeqAn 2.2.0. Is it possible that this is the problem? Did you compile popins with SeqAn 2.2.0?

**Comment by AnnaAlk** [comment]
No, we used seqan-v2.3.2

**Comment by bkehr** [comment]
In this case using SeqAn 2.2.0 will fix the problem.

**Comment by AnnaAlk** [comment]
Thank you. We will try.

**Comment by jbsysadmin** [comment]
Birte:
Where does one find previous versions? I don't see a listing of tar / gzipped items, or mention of 2.2.0.

From: bkehr [mailto:notifications@github.com] Sent: Monday, April 24, 2017 10:56 AM To: bkehr/popins <popins@noreply.github.com> Cc: Alkelai, Anna <aa3857@cumc.columbia.edu>; Author <author@noreply.github.com> Subject: Re: [bkehr/popins] Error when running contig map and genotype (#2) In this case using SeqAn 2.2.0 will fix the problem.

**Comment by jbsysadmin** [comment]
I found http://packages.seqan.de after some digging. Thanks.

**Comment by bkehr** [comment]
This is an old link, but it should still work.

I recommend going to the SeqAn GitHub page, where you currently can find 22 releases, one of which is seqan-v2.2.0:
https://github.com/seqan/seqan/releases

**Comment by AnnaAlk** [comment]
Can you please explain the values in the final vcf file, especially for ALT and INFO columns:

#CHROM

POS

ID

REF

ALT

QUAL

FILTER

INFO

1

726104

1:726104:FP

A

A[COMPONENT_947_a_length_353_size_5f:135[

.

.

AR=2;AS=0.5;GS=1

1

725161

1:725161:FP

G

]COMPONENT_947_a_length_353_size_5f:277]G

.

.

NOANCHOR

**Comment by bkehr** [comment]
Dear Anna,

could you please open a new issue as this is unrelated to the original problem.

Thanks,
Birte
