### ISSUE TITLE
contigmap ERROR：ERROR while sorting *bam by beginPos using samtools

### ISSUE THREAD

**Issue by nanshanjin** [bkehr/popins#22]
HI：
    when I run the step contigmap，there are same ERROR as：
[main] CMD: bwa mem -a -t 4 supercontigs.fa ./single.fastq
[main] Real time: 2252.959 sec; CPU: 8890.031 sec
[PopIns 2021-01-07 11:59:05] Filling in sequences of secondary records in bwa output
[PopIns 2021-01-07 12:27:50] Sorting .contig_mapped_unsorted.bam by read name using samtools
[bam_sort_core] merging from 0 files and 4 in-memory blocks...
[PopIns 2021-01-07 13:07:21] Merging bam files ./non_ref.bam and ./contig_mapped.bam
[PopIns 2021-01-07 13:07:21]  - merging headers...
[PopIns 2021-01-07 13:07:27]  - writing header...
[PopIns 2021-01-07 13:07:27]  - merging read records...
[PopIns 2021-01-07 13:39:31] Sorting ./merged.bam using samtools
ERROR while sorting ./merged.bam by beginPos using samtools

could you explain whats the problem and how to fix it
thanks very much

**Comment by bkehr** [comment]
Hello nanshanjin,

this error occurs in a samtools command.
Can you provide me with the version of samtools you are using?
Does samtools ouput an error message if you run the command separately using the same number of threads and amount of memory? For example, if your contigmap command used `-t 4` and no `-m` option:
```samtools sort -@ 4 -m 768M -o ./non_ref_new.bam ./merged.bam```

**Comment by nanshanjin** [comment]
> Hello nanshanjin,
> 
> this error occurs in a samtools command.
> Can you provide me with the version of samtools you are using?
> Does samtools ouput an error message if you run the command separately using the same number of threads and amount of memory? For example, if your contigmap command used `-t 4` and no `-m` option:
> `samtools sort -@ 4 -m 768M -o ./non_ref_new.bam ./merged.bam`
