### ISSUE TITLE
empty popin merge output file

### ISSUE THREAD

**Issue by jaeyoungjang2** [bkehr/popins#5]
When I run popins merge command, the result file is always empty.
So I used -p option to specify the input directory, but the result was the same. (The supercontigs.fa file is empty.)

I checked below things.
1. 'ln -s /path/to/seqan seqan'
2. Install all prerequisites (bwa, velvet, samtools, and sickle).
3. Set the paths to bwa, velveth, velvetg, samtools, and sickle in the file popins.config
4. Note: Please check that you have used the correct version of SeqAn by running popins genotype -h. 
             The last line of the help message needs to be Seqan version: 2.2.0 .

I have contigs which is extracted from 700 samples.

The path of "contigs.fa" is as follows. 
output_dir / {sample} /contigs.fa

and than run this script.
"{path}/popins merge"
"{path}/popins merge -p output_dir/"

The results are shown below.

[PopIns 2019-01-28 16:37:22] Partitioning contigs
[PopIns 2019-01-28 16:37:22] - Indexing contigs
[PopIns 2019-01-28 16:37:22] - Aligning contigs
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[PopIns 2019-01-28 16:37:22] Number of pairwise comparisons: 0
[PopIns 2019-01-28 16:37:22] Number of valid alignments:     0
[PopIns 2019-01-28 16:37:22] There are 0 components.
[PopIns 2019-01-28 16:37:22] Added 0 singletons to components.
[PopIns 2019-01-28 16:37:22] Constructing supercontigs
[PopIns 2019-01-28 16:37:22] 0 components are merged from several contigs.
[PopIns 2019-01-28 16:37:22] 0 contigs did not align with any other contig.
[PopIns 2019-01-28 16:37:22] 0 components are branching, given up on 0 of them.
[PopIns 2019-01-28 16:37:22] popins merge finished in 0 seconds.

**Comment by bkehr** [comment]
``path/to/popins merge -p output_dir/`` should be the correct command to use.

It seems that PopIns does not find any contig files to merge. Can you check that the contig files are present by listing them using

   ``ls -l output_dir/*/contigs.fa``

**Comment by jaeyoungjang2** [comment]
I did it.
and they all exists.

When i use this command(ls -l output_dir/*/contigs.fa), I found 700 hundred contigs.fa file
![20190130_113118](https://user-images.githubusercontent.com/47101085/51954189-97a48200-2482-11e9-9b61-0def91e4a3de.png)

Is there anything I missed...?

**Comment by bkehr** [comment]
Dear Bioinfo12342,

I need some more information from you in order to be able to help you.

 What are your sample directories called? Are they within the ``output_dir/`` or in the same folder as ``output_dir/``? Could you send me a full line of the output from the ``ls -l`` command?

**Comment by jaeyoungjang2** [comment]
![image](https://user-images.githubusercontent.com/47101085/51969695-7068a780-24b8-11e9-98c9-e8126d65751a.png)

The structure of the directory is as follows: /Project1/popintest/output_dir/{sample directory}/contigs.fa
700 samples are in the ouput_dir directory.
each sample directory contains contigs.fa.  This file is linked with the original file. (ln -s)

The popins merge command (path/to/popins merge -p /Project1/popintest/output_dir/) is executed in the "/Project1/popintest" directory and an empty file is created in "/Project1/popintest/supercontigs.fa"

**Comment by bkehr** [comment]
I am sorry, but I still don't understand why the command above does not find your files. Maybe I misunderstand your screenshot, but do you intend to merge the same fasta file with itself 700 times?

**Comment by jaeyoungjang2** [comment]
no. There are 700 different fasta files.
Each fasta contains different information.
Can I get a fasta file that I can test?
I'm sorry to botering you..

**Comment by bkehr** [comment]
Here is a very small test example:

```
$ mkdir test
$ cd test
$ mkdir sample1
$ mkdir sample2
$ echo -e '>sample1_contig1\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTTAGTCGCGTAGTCTTACTGGCTACTAGGCGATTCACGGAGCACGCATTTACGACTTTCGAGCAACCCGATCTATCTGAGCTATTCTACTGGCGTATCTATGCG' > sample1/contigs.fa
$ echo -e '>sample2_contig1\nCTTAGTCGCGTAGTCTTACTGGCTACTAGGCGATTCACGGAGCACGCATTTACGACTTTCGAGCAACCCGATCTATCTGAGCTATTCTACTGGCGTATCTATGCGCCCCCCCCCCCCCCCCCCCCCCCCCC' > sample2/contigs.fa
$ ~/work/code/popins/popins merge
[PopIns 2019-02-01 11:15:15] Loaded ./sample2/contigs.fa: 131 bp in 1 contigs
[PopIns 2019-02-01 11:15:15] Loaded ./sample1/contigs.fa: 135 bp in 1 contigs
[PopIns 2019-02-01 11:15:15] Partitioning contigs
[PopIns 2019-02-01 11:15:15] - Indexing contigs
[PopIns 2019-02-01 11:15:15] - Aligning contigs
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[PopIns 2019-02-01 11:15:15] Number of pairwise comparisons: 1
[PopIns 2019-02-01 11:15:15] Number of valid alignments:     1
[PopIns 2019-02-01 11:15:15] There are 1 components.
[PopIns 2019-02-01 11:15:15] Added 0 singletons to components.
[PopIns 2019-02-01 11:15:15] Constructing supercontigs
[PopIns 2019-02-01 11:15:15] 1 components are merged from several contigs.
[PopIns 2019-02-01 11:15:15] 0 contigs did not align with any other contig.
[PopIns 2019-02-01 11:15:15] 0 components are branching, given up on 0 of them.
[PopIns 2019-02-01 11:15:15] popins merge finished in 0 seconds.
$ cat supercontigs.fa
>COMPONENT_0_a_length_161_size_2
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTTAGTCGCGTAGTCTTACTGGCTACTAGGCGATTCACGGAGCACGCATTTACGACTTTCGAGCAACCCGATCTATCTGAGCTATTCTACTGGCGTATCTATGCGCCCCCCCCCCCCCCCCCCCCCCCCCC
```

**Comment by jaeyoungjang2** [comment]
sorry to late response.
When I first used the test sample, I still created an empty file.
After knowing that it was not a problem with the file, I checked the other part.
The result was a problem with the ubuntu version.
I have confirmed that it only works on ubuntu version 18 and not on ubuntu version 14 and 16.
Thank you for your help.
