### ISSUE TITLE
VCF parsing error in genotype subcommand

### ISSUE THREAD

**Issue by alexandervogel** [bkehr/popins#9]
Running the following genotype command resulted in an error related toe the seqan library (see output below):
`
popins genotype \
> -p ./samples/ \
> -r ./ref/genome.fa \
> -i ./insertions.vcf \
> -c ./supercontigs.fa \
> Sample_0000
`

Output:
`
[PopIns 2019-05-20 10:35:44] Opening input files.
[PopIns 2019-05-20 10:35:44] Genotyping VCF records in './insertions.vcf' for Sample_0000.
terminate called after throwing an instance of 'seqan::ParseError'
  what():  Not enough values in a line.
Aborted
`

Looking into the seqan/include/seqan/vcf_io/read_vcf.h  code indicates that it seems to expects at least 8 columns while the insertions.vcf file only contains 7. Changing the following if statement in seqan to <7 and recompiling solved the issue for me:

`    if (length(field_values) < 8u + numSamples)
SEQAN_THROW(ParseError("Not enough values in a line."));`

**Comment by bkehr** [comment]
Could it be that you are using a version of SeqAn that is 2.3.0 or later? PopIns requires version 2.2.0.
The SeqAn version is indicated in the help message, i.e. the output of ``popins genotype -h``.

**Comment by alexandervogel** [comment]
Thanks a lot for the quick reply. Recompiling with 2.2.0 did the trick. I do however get a new error but will raise a new issue for this.
